import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/SessionProvider";

const garamond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-garamond",
});

export const metadata: Metadata = {
  title: "Pansophia — AI-Powered Learning",
  description: "Personalized courses generated by AI, tailored to your learning style and goals.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${garamond.variable} h-full`}>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
